input.onButtonPressed(Button.A, function () {
    for (let index = 0; index < input.runningTime(); index++) {
        pins.servoWritePin(AnalogPin.P0, 180)
        basic.pause(1000)
        pins.servoWritePin(AnalogPin.P0, 0)
        basic.pause(10000)
    }
})
input.onButtonPressed(Button.B, function () {
    basic.showNumber(Math.trunc(input.runningTime() / 3600000))
    basic.showString("H")
    basic.clearScreen()
    basic.showNumber(Math.trunc(input.runningTime() / 60000) % 60)
    basic.showString("M")
    basic.clearScreen()
    basic.showNumber(Math.trunc(input.runningTime() / 1000) % 60)
    basic.showString("S")
    basic.clearScreen()
})
music.setVolume(255)
basic.showNumber(9)
basic.showNumber(8)
basic.showNumber(7)
basic.showNumber(6)
basic.showNumber(5)
basic.showNumber(4)
basic.showNumber(3)
basic.showNumber(2)
basic.showNumber(1)
basic.showNumber(0)
basic.clearScreen()
basic.showString("OK")
basic.showString("START")
